/* 
 * PI Web API 2016 R2 Swagger definition
 *
 * RESTful client for PI Web API 2016 R2
 *
 * OpenAPI spec version: v1
 * Contact: pidevclub@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Reflection;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Newtonsoft.Json;

namespace OSIsoft.PIDevClub.PIWebApiClient.Client
{
    /// <summary>
    /// Represents a set of configuration settings
    /// </summary>
    public class Configuration
    {
        public Configuration(ApiClient client)
        {
            this.ApiClient = client;
            DefaultHeader = new Dictionary<string, string>();
        }

        public IDictionary<string, string> DefaultHeader { get; set; }
        public ApiClient ApiClient { get; private set; }
        public Configuration Default { get; internal set; }

        internal static Exception DefaultExceptionFactory(string methodName, IRestResponse response)
        {
            int status = (int)response.StatusCode;
            if (status >= 400) return new ApiException(status, String.Format("Error calling {0}: {1}", methodName, response.StringContent), response.JsonContent);
            if (status == 0) return new ApiException(status, String.Format("Error calling {0}: {1}", methodName, response.StringContent), response.JsonContent);
            return null;
        }
    }
}
