/* 
 * PI Web API 2016 R2 Swagger definition
 *
 * RESTful client for PI Web API 2016 R2
 *
 * OpenAPI spec version: v1
 * Contact: pidevclub@osisoft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;

namespace OSIsoft.PIDevClub.PIWebApiClient.Client
{
    internal class RestResponse : IRestResponse
    {
        private HttpResponseMessage response;

        public RestResponse()
        {
        }

        public RestResponse(HttpResponseMessage response)
        {
            this.response = response;
            Stream stream = response.Content.ReadAsStreamAsync().Result;
            StreamReader streamReader = new StreamReader(stream);
            StringContent = streamReader.ReadToEndAsync().Result;
            JsonContent = JsonConvert.DeserializeObject<dynamic>(this.StringContent);
        }
        public bool IsSuccessful => response.IsSuccessStatusCode;
        public HttpStatusCode StatusCode { get => response.StatusCode; }
        public HttpContent Content { get => response.Content; }
        public string StatusDescription { get => response.ReasonPhrase; }
        public Version ProtocolVersion { get => response.Version; }
        public HttpResponseHeaders Headers { get => response.Headers; }
        public string StringContent { get; }
        public dynamic JsonContent { get; }
    }
}